/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro", // document ID
      label: "Capítulo 1", // sidebar label
    },
    {
      type: "category",
      label: "Clãs",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "clas/index" },
      items: [
        {
          type: "doc",
          id: "clas/assamita",
          label: "Assamitas",
        },
        {
          type: "doc",
          id: "clas/brujah",
          label: "Brujah",
        },
        {
          type: "doc",
          id: "clas/capadocio",
          label: "Capadócio",
        },
        {
          type: "doc",
          id: "clas/gangrel",
          label: "Gangrel",
        },
        {
          type: "doc",
          id: "clas/lasombra",
          label: "Lasombra",
        },
        {
          type: "doc",
          id: "clas/malkavianos",
          label: "Malkavianos",
        },
        {
          type: "doc",
          id: "clas/nosferatus",
          label: "Nosferatus",
        },
        {
          type: "doc",
          id: "clas/ravnos",
          label: "Ravnos",
        },
        {
          type: "doc",
          id: "clas/setistas",
          label: "Seguidores de Set",
        },
        {
          type: "doc",
          id: "clas/toreador",
          label: "Toreadores",
        },
        {
          type: "doc",
          id: "clas/tremere",
          label: "Tremere",
        },
        {
          type: "doc",
          id: "clas/tzimisce",
          label: "Tzimisce",
        },
        {
          type: "doc",
          id: "clas/ventrue",
          label: "Venture",
        },
        {
          type: "doc",
          id: "clas/caitiff",
          label: "Caitiff",
        },
      ],
    },
    {
      type: "doc",
      id: "criação-de-personagem",
      label: "Criando seu personagem",
    },
    {
      type: "category",
      label: "Glossário",
      collapsible: true,
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Glossário",
        description: "Learn about the most important Docusaurus concepts!",
        slug: "glossário",
        keywords: ["glossario"],
      },
      items: ["voc_comum", "voc_arcaico"],
    },
  ],
  */
};

module.exports = sidebars;
